// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKf6v0yHIueypiMR--sBpi8hByy0VenqM',
    appId: '1:40551802364:web:354a1339c3d5e92cc67e79',
    messagingSenderId: '40551802364',
    projectId: 'todolist-fire-eae74',
    authDomain: 'todolist-fire-eae74.firebaseapp.com',
    storageBucket: 'todolist-fire-eae74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIEDxZYybVtSCt7xUCDAdJbs3eTS8-vaw',
    appId: '1:40551802364:android:146ba1ccc1f2a3cec67e79',
    messagingSenderId: '40551802364',
    projectId: 'todolist-fire-eae74',
    storageBucket: 'todolist-fire-eae74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzhZL0FbGcP-kJa_5UhF5MMMtzZIunxZ0',
    appId: '1:40551802364:ios:2e8c2bccf18a8527c67e79',
    messagingSenderId: '40551802364',
    projectId: 'todolist-fire-eae74',
    storageBucket: 'todolist-fire-eae74.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzhZL0FbGcP-kJa_5UhF5MMMtzZIunxZ0',
    appId: '1:40551802364:ios:2e8c2bccf18a8527c67e79',
    messagingSenderId: '40551802364',
    projectId: 'todolist-fire-eae74',
    storageBucket: 'todolist-fire-eae74.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKf6v0yHIueypiMR--sBpi8hByy0VenqM',
    appId: '1:40551802364:web:354a1339c3d5e92cc67e79',
    messagingSenderId: '40551802364',
    projectId: 'todolist-fire-eae74',
    authDomain: 'todolist-fire-eae74.firebaseapp.com',
    storageBucket: 'todolist-fire-eae74.appspot.com',
  );

}